import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { ReactNode } from "react";
import Navigation from "./../components/Navigation";
import Footer from "./../components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Mikael Paczkowski',
  description: 'Generated by create next app',
}



interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Navigation />
      <body className={`${inter.className} bg-slate-900 text-slate-100 container mx-auto p-4`}>{children}</body>
      <Footer />
    </>
  );
};

export default Layout;
